Repository RAF-SI-2024/Banka-4-Backend, pull requests merged in 2025-03, with the labels that each got.

#138 Add owners file
  OWNERS
Labels: size/S

#139 user-service: emit longer tokens in dev
  user-service/src/main/resources/application-dev.yml
Labels: approved, size/XS, lgtm

#137 Add new information in loanInformationDto
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanInformationDto.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/LoanServiceMock.java
  user-service/src/test/java/rs/banka4/user_service/generator/LoanObjectMother.java
Labels: size/M, approved, lgtm

#141 Feature/get all loans
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/LoanDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanStatus.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanType.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanFilterDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/specification/LoanSpecification.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/InvalidLoanStatus.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/InvalidLoanType.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/LoanService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/LoanServiceMock.java
  user-service/src/test/java/rs/banka4/user_service/routes/LoanControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/GetAllLoansTests.java
Labels: approved, lgtm, size/L

#140 :sparkles: Implemented new changes from refactor, and removed event i…
  user-service/build.gradle.kts
  user-service/src/main/java/rs/banka4/user_service/controller/TotpController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/TotpControllerDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/authenticator/db/SentCode.java
  user-service/src/main/java/rs/banka4/user_service/domain/authenticator/db/UserTotpSecret.java
  user-service/src/main/java/rs/banka4/user_service/domain/authenticator/dtos/RegenerateAuthenticatorResponseDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/dtos/CreateCardDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreatePaymentDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreateTransactionDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/ClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/mapper/ClientMapper.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/account/AccountNotActive.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/authenticator/NoTotpException.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/authenticator/NotActiveTotpException.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/authenticator/NotValidTotpException.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/transaction/TransactionInvalidOrAlreadyProcessed.java
  user-service/src/main/java/rs/banka4/user_service/repositories/TransactionRepository.java
  user-service/src/main/java/rs/banka4/user_service/repositories/UserTotpSecretRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/TotpAbs.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/ClientServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TotpService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/AccountObjectMother.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/ClientObjectMother.java
  user-service/src/main/resources/db/migration/V13__user_to_totp_secrets.sql
  user-service/src/test/java/rs/banka4/user_service/generator/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/ClientObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/TransactionObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/authenticator/TotpServiceTest.java
  user-service/src/test/java/rs/banka4/user_service/unit/client/ClientServiceCreateTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/client/ClientServiceGetTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceCreateTests.java
Labels: approved, size/XL, lgtm

#144 Replace System.out.println with logger
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/EmployeeServiceImpl.java
Labels: size/S, approved, lgtm

#142 Feature/manage loans
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/LoanDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/jwt/Unauthorized.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/LoanService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/LoanServiceMock.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ManageLoansTests.java
Labels: approved, lgtm, size/L

#132 Integrate exchange office cache service by @mbaclija1921rn
  .gitignore
  README.md
  docker-compose.yml
  docker/Dockerfile-exchange-office
  docker/exchange-config.py
  docker/gateway-nginx.conf
  exchange-office/.dockerignore
  exchange-office/.gitignore
  exchange-office/LICENSE
  exchange-office/banka4_exchange/.dockerignore
  exchange-office/banka4_exchange/__init__.py
  exchange-office/banka4_exchange/wsgi.py
  exchange-office/instance/.gitignore
  exchange-office/instance/config.py.example
  exchange-office/openapi.yaml
  exchange-office/pyproject.toml
  exchange-office/tests/conftest.py
  exchange-office/tests/test_all.py
  exchange-office/tests/test_exchange.json
  user-service/build.gradle.kts
Labels: approved, size/XL, lgtm

#150 Genders are arbitrary
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/CreateClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/UpdateClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/mapper/ClientMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/CreateEmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/UpdateEmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/mapper/EmployeeMapper.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/ErrorResponseHandler.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/ClientObjectMother.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/EmployeeObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/ClientObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/EmployeeObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/client/ClientServiceUpdateTests.java
Labels: size/M, approved, lgtm

#149 Block, unblock and deactivate card endpoints
  user-service/src/main/java/rs/banka4/user_service/controller/CardController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/CardDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/db/Card.java
  user-service/src/main/java/rs/banka4/user_service/repositories/CardRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/CardService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/CardServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/CardServiceMock.java
  user-service/src/main/resources/db/migration/V14__rename_limit_column.sql
  user-service/src/test/java/rs/banka4/user_service/routes/CardControllerTests.java
Labels: approved, lgtm, size/L

#152 user/loan: fix search loans endpoint
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
Labels: approved, size/XS, lgtm

#153 user/account: fix account not active
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
Labels: approved, size/XS, lgtm

#155 user/transaction: add new contact on payment or transfer
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreatePaymentDto.java
  user-service/src/main/java/rs/banka4/user_service/repositories/ClientContactRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/generator/TransactionObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceCreateTests.java
Labels: size/M, approved, lgtm

#156 user/transaction: fix payment status
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
Labels: approved, size/XS, lgtm

#157 Feature/loan rate calculation
  notification-service/src/main/java/rs/banka4/notification_service/email/EmailService.java
  notification-service/src/main/java/rs/banka4/notification_service/email/Subjects.java
  notification-service/src/main/resources/application.properties
  notification-service/src/main/resources/templates/loan-installment-paid.html
  notification-service/src/main/resources/templates/loan-installment-paid.txt
  notification-service/src/main/resources/templates/loan-installment-payment-denied.html
  notification-service/src/main/resources/templates/loan-installment-payment-denied.txt
  notification-service/src/main/resources/templates/loan-penalty.html
  notification-service/src/main/resources/templates/loan-penalty.txt
  user-service/src/main/java/rs/banka4/user_service/UserServiceApplication.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/BankMargin.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/InterestRate.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/Loan.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanInformationDto.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/LoanTypeNotFound.java
  user-service/src/main/java/rs/banka4/user_service/repositories/BankMarginRepository.java
  user-service/src/main/java/rs/banka4/user_service/repositories/InterestRateRepository.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanInstallment.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanInstallmentRepository.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/LoanService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/CardServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/JwtUtil.java
  user-service/src/main/java/rs/banka4/user_service/utils/MessageHelper.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanInstallmentScheduler.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanRateScheduler.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanRateUtil.java
  user-service/src/main/resources/db/migration/V15__interest_rates.sql
  user-service/src/test/java/rs/banka4/user_service/unit/loan/LoanInstallmentSchedulerTest.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/LoanRateUnitTest.java
Labels: approved, lgtm, size/XXL

#158 Bugfix/transactions filter by account number
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/specification/SpecificationCombinator.java
Labels: size/S, approved, lgtm

#161 user/transaction: fix transfer money dtos and database handle
  user-service/src/main/java/rs/banka4/user_service/controller/TransactionController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/TransactionApiDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreateTransferDto.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/TransactionService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/generator/TransactionObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceCreateTests.java
Labels: approved, lgtm, size/L

#159 Bag/manage loans new
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanInstallment.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanInstallmentScheduler.java
  user-service/src/main/resources/db/migration/V16__loan_installment_alter.sql
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ManageLoansTests.java
Labels: size/M, approved, lgtm

#160 Feature/request credit
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/LoanDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanRequest.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanApplicationDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanInfoDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/mapper/LoanMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/specification/LoanSpecification.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/account/AccountNotActive.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/account/AccountNotFound.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/NoLoansOnAccount.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRepository.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRequestRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/LoanService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/LoanServiceMock.java
  user-service/src/main/java/rs/banka4/user_service/utils/specification/LoanSpecification.java
  user-service/src/main/java/rs/banka4/user_service/utils/specification/SpecificationCombinator.java
  user-service/src/main/resources/db/migration/V16__loan_requests.sql
  user-service/src/test/java/rs/banka4/user_service/generator/LoanObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/routes/LoanControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/CreateLoanTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/GetAllLoansTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ListingLoansTests.java
Labels: approved, size/XL, lgtm

#162 Hotfix for service
  user-service/src/main/java/rs/banka4/user_service/domain/loan/mapper/LoanMapper.java
  user-service/src/main/resources/db/migration/V17__loan_requests.sql
Labels: size/S, approved, lgtm

#163 Bag/get all loans new
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/LoanDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanApplicationResponseDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/mapper/LoanMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/specification/LoanSpecification.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRequestRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/LoanService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/LoanServiceMock.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/GetAllLoansTests.java
Labels: approved, lgtm, size/L

#164 user/loans: fix issues with loans
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/LoanDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanRequest.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanApplicationDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanApplicationResponseDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanInfoDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanInformationDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/mapper/LoanMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/specification/LoanSpecification.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/ErrorResponseHandler.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/InterestRateAmountNotSupported.java
  user-service/src/main/java/rs/banka4/user_service/repositories/LoanRequestRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/LoanService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/LoanServiceMock.java
  user-service/src/test/java/rs/banka4/user_service/generator/LoanObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/routes/LoanControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/GetAllLoansTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ListingLoansTests.java
Labels: approved, lgtm, size/L

#154 Feature/card creation endpoint
  user-service/src/main/java/rs/banka4/user_service/controller/CardController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/AccountApiDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/CardDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/account/dtos/CreateAccountDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/db/AuthorizedUser.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/db/Card.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/dtos/CreateCardDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/mapper/CardMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/mapper/ClientMapper.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/card/AuthorizedUserNotAllowed.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/card/CardLimitExceededException.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/card/DuplicateAuthorizationException.java
  user-service/src/main/java/rs/banka4/user_service/repositories/CardRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/AccountService.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/CardService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/CardServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/CardServiceMock.java
  user-service/src/test/java/rs/banka4/user_service/generator/CardObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/routes/AccountControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/CardControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/account/AuthServiceTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/card/CardServiceTests.java
Labels: approved, size/XL, lgtm

#165 user/account: fix account mapper currency handler
  user-service/src/main/java/rs/banka4/user_service/domain/account/dtos/AccountDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/account/mapper/AccountMapper.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/AccountObjectMother.java
Labels: approved, size/XS, lgtm

#177 Add Javadoc comments for filters
  user-service/src/main/java/rs/banka4/user_service/config/filters/ExceptionHandlingFilter.java
  user-service/src/main/java/rs/banka4/user_service/config/filters/InvalidRouteFilter.java
  user-service/src/main/java/rs/banka4/user_service/config/filters/JwtAuthenticationFilter.java
  user-service/src/main/java/rs/banka4/user_service/config/filters/RateLimitingFilter.java
Labels: size/M, approved, lgtm

#166 Add more tests
  user-service/src/test/java/rs/banka4/user_service/generator/ClientObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/CompanyObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/TransactionObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/routes/AccountControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/ClientContactControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/ClientControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/EmployeeControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/LoanControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/TotpControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/TransactionControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/account/AccountServiceCreateTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/account/AccountServiceFilterTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/account/AccountServiceGetTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/client/ClientContactServiceTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceGetTests.java
  user-service/src/test/java/rs/banka4/user_service/util/MockMvcUtil.java
Labels: approved, lgtm, size/XXL

#180 Bugfix - save method called two times
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/routes/CardControllerTests.java
Labels: approved, size/XS, lgtm

#148 re-add missing line endings on EOF
  .editorconfig
Labels: size/S, approved, lgtm

#178 add docs for LoanInstallmentScheduler and LoanRateScheduler
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanInstallmentScheduler.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanRateScheduler.java
Labels: size/M, approved, lgtm

#181 fix: change back currency in AccountDto to CurrencyDto
  user-service/src/main/java/rs/banka4/user_service/domain/account/dtos/AccountDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/account/mapper/AccountMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/currency/dtos/CurrencyDto.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ListingLoansTests.java
Labels: size/S, approved, lgtm

#182 user/contacts: get list of all contacts for specific client
  user-service/src/main/java/rs/banka4/user_service/controller/ClientContactController.java
  user-service/src/main/java/rs/banka4/user_service/repositories/ClientContactRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/ClientContactService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/ClientContactServiceImpl.java
Labels: approved, lgtm

#183 user/client: fix crash on phone query
  user-service/src/main/java/rs/banka4/user_service/utils/specification/ClientSpecification.java
Labels: approved, size/XS, lgtm

#184 loan Installment fix
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
Labels: size/S, approved, lgtm

#185 fix: getAllLoansProcessing
  user-service/src/main/java/rs/banka4/user_service/domain/loan/specification/LoanSpecification.java
Labels: approved, size/XS, lgtm

#195 Resolve issues with currencies
  user-service/src/main/java/rs/banka4/user_service/controller/AccountController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/AccountApiDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/account/dtos/AccountClientIdDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/account/dtos/SetAccountLimitsDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/dtos/CreateAuthorizedUserDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanApplicationResponseDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/dtos/LoanInformationDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/mapper/LoanMapper.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/ClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/CreateClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/UpdateClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/CreateEmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/EmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/EmployeeResponseDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/UpdateEmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/AccountService.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/CardService.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/TotpService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TotpServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/LoanObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/routes/AccountControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/account/AccountServiceImplSetLimitsTest.java
  user-service/src/test/java/rs/banka4/user_service/unit/authenticator/TotpServiceImplTest.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/GetAllLoansTests.java
Labels: approved, size/XL, lgtm

#200 user/account: change account default account limit
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
Labels: approved, size/XS, lgtm

#206 Implement exchange rates into transactions and transfers
  user-service/src/main/java/rs/banka4/user_service/config/RestTemplateConfig.java
  user-service/src/main/java/rs/banka4/user_service/controller/TransactionController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/TransactionApiDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/currency/db/Currency.java
  user-service/src/main/java/rs/banka4/user_service/domain/exchange/dtos/ExchangeRate.java
  user-service/src/main/java/rs/banka4/user_service/domain/exchange/dtos/ExchangeRateDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/db/Transaction.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreatePaymentDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreateTransactionDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreateTransferDto.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/transaction/ExceededDailyLimit.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/transaction/ExceededMonthlyLimit.java
  user-service/src/main/java/rs/banka4/user_service/repositories/AccountRepository.java
  user-service/src/main/java/rs/banka4/user_service/repositories/TransactionRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/BankAccountService.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/TransactionService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/BankAccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/ExchangeRateService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/specification/PaymentSpecification.java
  user-service/src/main/resources/db/migration/V18__add_is_transfer_to_tx.sql
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceCreateTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceProcessingTests.java
Labels: approved, lgtm, size/XXL

#207 test-conventions: put jacocoIntegrationTestReport in verification group
  buildSrc/src/main/kotlin/banka4.test-conventions.gradle.kts
Labels: approved, size/XS, lgtm

#208 user/card: fix and add tests for card actions
  user-service/src/test/java/rs/banka4/user_service/unit/card/CardServiceCardActionsTests.java
Labels: bug, approved, lgtm

#209 ci: use images with gradle installed
  .prow/code-formatter.yml
  .prow/user-service.yml
  docker-compose.yml
Labels: size/M, approved, lgtm

#211 stock: new mICroSeRvICe
  docker-compose.yml
  docker/gateway-nginx.conf
  settings.gradle.kts
  stock-service/.dockerignore
  stock-service/.gitignore
  stock-service/build.gradle.kts
  stock-service/src/main/java/rs/banka4/stock_service/StockServiceApplication.java
  stock-service/src/main/resources/application-dev.yml
  stock-service/src/main/resources/application.properties
  stock-service/src/test/java/rs/banka4/stock_service/StockServiceApplicationTests.java
  stock-service/src/test/resources/application.yml
Labels: approved, lgtm, size/L

#214 Bugfix/employee search account number
  user-service/src/main/java/rs/banka4/user_service/controller/CardController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/CardDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/CardService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/CardServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/CardServiceMock.java
  user-service/src/main/java/rs/banka4/user_service/utils/specification/CardSpecification.java
  user-service/src/test/java/rs/banka4/user_service/unit/card/CardServiceEmployeeSearchCardTests.java
Labels: size/M, approved, lgtm

#210 user-service: improve loan requests seeder
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
Labels: size/M, approved, lgtm

#218 Fix: transfer to same account blocked
  user-service/src/main/java/rs/banka4/user_service/exceptions/transaction/ClientCannotTransferToSameAccount.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/specification/PaymentSpecification.java
  user-service/src/test/java/rs/banka4/user_service/generator/TransactionObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceCreateTests.java
Labels: size/M, approved, lgtm

#222 apply spotless add tests and fix bug
  user-service/src/main/java/rs/banka4/user_service/service/impl/CardServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/unit/card/CardServiceTests.java
Labels: approved, lgtm, size/L

#221 user/refactor: improve seeders for all entities
  user-service/src/main/java/rs/banka4/user_service/repositories/AccountRepository.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/AccountService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
Labels: approved, lgtm

#223 Feature/Squashed/ Develop a Stock Market Trading Microservice #215
  stock-service/src/main/java/rs/banka4/stock_service/controller/ExchangeController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/SecuritiesController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/ExchangeApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/ListingApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/SecuritiesApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/exchanges/db/Exchange.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/exchanges/dtos/ExchangeDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/exchanges/mapper/ExchangeMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/Listing.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/ListingDailyPriceInfo.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/ListingDailyPriceInfoDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/ListingDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/mapper/ListingDailyPriceInfoMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/mapper/ListingMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/Security.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/SecurityDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/SecurityMapperImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/db/CurrencyCode.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/db/ForexLiquidity.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/db/ForexPair.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/dtos/ForexPairDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/mapper/ForexPairMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/future/db/Future.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/future/db/UnitName.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/future/dtos/FutureDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/future/mapper/FutureMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/stock/db/Stock.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/stock/dtos/StockDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/stock/mapper/StockMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ExchangeRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ForexRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/FutureRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingDailyPriceInfoRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/StockRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/runners/TestDataRunner.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/ExchangeService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/ListingService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/SecuritiesService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/ExchangeServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/ListingServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/SecuritiesServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/ExchangeServiceMock.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/ListingServiceMock.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/SecuritiesServiceMock.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/ExchangeObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/ForexPairObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/FutureObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/ListingObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/SecuritiesObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/StockObjectMother.java
  stock-service/src/main/resources/db/migration/V1__INIT_STOCKSERVICE.sql
  stock-service/src/test/java/rs/banka4/stock_service/StockServiceApplicationTests.java
Labels: approved, lgtm, size/XXL

#224 ci: don't check all commits for good formatting
  .prow/code-formatter.yml
Labels: size/S, approved, lgtm

#227 .
  .editorconfig
  user-service/src/main/java/rs/banka4/user_service/domain/account/db/Account.java
  user-service/src/main/java/rs/banka4/user_service/domain/auth/db/Token.java
  user-service/src/main/java/rs/banka4/user_service/domain/authenticator/db/UserTotpSecret.java
  user-service/src/main/java/rs/banka4/user_service/domain/card/db/Card.java
  user-service/src/main/java/rs/banka4/user_service/domain/company/db/ActivityCode.java
  user-service/src/main/java/rs/banka4/user_service/domain/company/db/Company.java
  user-service/src/main/java/rs/banka4/user_service/domain/currency/db/Currency.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/BankMargin.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/InterestRate.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/Loan.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanInstallment.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanRequest.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/db/Transaction.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/User.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/db/ClientContact.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/AccountObjectMother.java
  user-service/src/main/resources/db/migration/V19__remove_currency_version.sql
  user-service/src/test/java/rs/banka4/user_service/generator/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/LoanObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/GetAllLoansTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ListingLoansTests.java
Labels: approved, lgtm, size/L

#225 user-service-fix: tx toAmount value
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceCreateTests.java
Labels: size/M, approved, lgtm

#229 editorconfig: fix indent_style copy-pasto for *.java files
  .editorconfig
Labels: approved, size/XS, lgtm

#230 Fix/loans remove money
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/BankAccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanInstallmentScheduler.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/LoanInstallmentSchedulerTest.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ManageLoansTests.java
Labels: approved, lgtm, size/L

#231 add filter for rejected loan requests
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
Labels: approved, size/XS, lgtm

#232 stock: return integration test
  stock-service/src/test/java/rs/banka4/stock_service/StockServiceApplicationTests.java
Labels: size/M, approved, lgtm

#233 stock: add ci
  .prow/stock-service.yml
Labels: size/M, approved, lgtm

#234 simplify migrations
  README.md
  buildSrc/src/main/kotlin/banka4.migration-generator.gradle.kts
  stock-service/build.gradle.kts
  stock-service/src/main/resources/application.properties
  user-service/build.gradle.kts
  user-service/src/main/resources/application.properties
Labels: size/M, approved, lgtm

#235 Refactor role and privilege handling
  user-service/src/main/java/rs/banka4/user_service/config/SecurityConfig.java
  user-service/src/main/java/rs/banka4/user_service/domain/auth/db/SecuredUser.java
  user-service/src/main/java/rs/banka4/user_service/utils/JwtUtil.java
Labels: size/M, approved, lgtm

#236 common: new module, library for common code
  .prow/stock-service.yml
  .prow/user-service.yml
  common/build.gradle.kts
  common/src/main/java/rs/banka4/rafeisen/common/.gitkeep
  settings.gradle.kts
  stock-service/build.gradle.kts
  user-service/build.gradle.kts
Labels: size/M, approved, lgtm

#237 stock-service: redo database model
  stock-service/src/main/java/rs/banka4/stock_service/domain/actuaries/db/ActuaryInfo.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/actuaries/db/MonetaryAmount.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/Listing.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/Asset.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/Option.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/OptionType.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/Direction.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/Order.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/OrderType.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/Status.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/Security.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/db/ForexPair.java
  stock-service/src/main/java/rs/banka4/stock_service/runners/TestDataRunner.java
  stock-service/src/main/resources/application.properties
  stock-service/src/main/resources/db/migration/V2025.57.30.1743303477__nuke_db_and_make_new.sql
  stock-service/src/test/java/rs/banka4/stock_service/StockServiceApplicationTests.java
Labels: approved, lgtm, size/L

#244 docker: add support for the common module
  common/.dockerignore
  docker-compose.yml
  docker/Dockerfile-java
Labels: size/S, approved, lgtm

#212 Feature/integration tests
  user-service/src/test/java/rs/banka4/user_service/integration/ApproveLoanTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/BlockCardTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/CreateAccountTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/DeactivateCardTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/GetAllClientsTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/GetAllLoansTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/LoginTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/RejectLoanTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/SearchAllLoansTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/UnBlockCardTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/seeder/TestDataSeeder.java
Labels: approved, lgtm, size/XXL

#251 Stop using DaoAuthenticationProvider
  user-service/src/main/java/rs/banka4/user_service/config/ApplicationConfig.java
  user-service/src/main/java/rs/banka4/user_service/config/filters/JwtAuthenticationFilter.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/User.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/db/Client.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/db/Employee.java
  user-service/src/main/java/rs/banka4/user_service/security/AuthenticatedBankUserAuthentication.java
  user-service/src/main/java/rs/banka4/user_service/security/AuthenticatedBankUserPrincipal.java
  user-service/src/main/java/rs/banka4/user_service/security/BankUserAuthProvider.java
  user-service/src/main/java/rs/banka4/user_service/security/PreAuthBankUserAuthentication.java
  user-service/src/main/java/rs/banka4/user_service/security/UnauthenticatedBankUserPrincipal.java
  user-service/src/main/java/rs/banka4/user_service/security/UserType.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/ClientServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/CustomUserDetailsService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/EmployeeServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/utils/JwtUtil.java
  user-service/src/main/java/rs/banka4/user_service/utils/loans/LoanRateScheduler.java
  user-service/src/test/java/rs/banka4/user_service/routes/AccountControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/AuthControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/CardControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/ClientContactControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/ClientControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/EmployeeControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/LoanControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/NoopJwtAuthenticationFilter.java
  user-service/src/test/java/rs/banka4/user_service/routes/TotpControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/routes/TransactionControllerTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/client/ClientServiceCreateTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/employee/EmployeeServiceTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/filters/RoutesFilterTests.java
Labels: approved, size/XL, lgtm

#245 stock-service testdataunner setup
  stock-service/src/main/java/rs/banka4/stock_service/domain/exchanges/db/Exchange.java
  stock-service/src/main/java/rs/banka4/stock_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
Labels: approved, size/XL, lgtm

#253 Remove unused permissions, and move privileges into common code
  common/src/main/java/rs/banka4/rafeisen/common/security/Privilege.java
  user-service/src/main/java/rs/banka4/user_service/domain/account/dtos/AccountClientIdDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/Privilege.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/PrivilegesDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/User.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/ClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/CreateClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/client/dtos/UpdateClientDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/CreateEmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/EmployeeResponseDto.java
  user-service/src/main/java/rs/banka4/user_service/domain/user/employee/dtos/UpdateEmployeeDto.java
  user-service/src/main/java/rs/banka4/user_service/runners/TestDataRunner.java
  user-service/src/main/java/rs/banka4/user_service/security/AuthenticatedBankUserAuthentication.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/EmployeeServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/AccountObjectMother.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/ClientObjectMother.java
  user-service/src/main/java/rs/banka4/user_service/service/mock/generators/EmployeeObjectMother.java
  user-service/src/main/java/rs/banka4/user_service/utils/SecurityUtils.java
  user-service/src/main/resources/db/migration/V2025.47.31.1743446860__removed_unused_privileges.sql
  user-service/src/test/java/rs/banka4/user_service/generator/AccountObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/ClientObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/generator/EmployeeObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/unit/client/ClientServiceUpdateTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/employee/EmployeeServiceTests.java
Labels: approved, lgtm, size/L

#258 Clean up JsonCreators and `Invalid{Loan{Type,Status},Currency}` exceptions
  user-service/src/main/java/rs/banka4/user_service/controller/LoanController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/AccountApiDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/LoanDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/currency/db/Currency.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanStatus.java
  user-service/src/main/java/rs/banka4/user_service/domain/loan/db/LoanType.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/account/InvalidCurrency.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/InvalidLoanStatus.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/InvalidLoanType.java
  user-service/src/main/java/rs/banka4/user_service/exceptions/loan/LoanAlreadyJudged.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/AccountServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/LoanServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/generator/TransactionObjectMother.java
  user-service/src/test/java/rs/banka4/user_service/integration/RejectLoanTest.java
  user-service/src/test/java/rs/banka4/user_service/unit/account/AccountServiceCreateTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/loan/ManageLoansTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceGetTests.java
  user-service/src/test/java/rs/banka4/user_service/unit/transaction/TransactionServiceProcessingTests.java
Labels: approved, lgtm, size/L

#259 feature/refactor-exchange-database
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/Listing.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/ListingDailyPriceInfo.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/Asset.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/Security.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/SecurityDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/SecurityMapperImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/forex/dtos/ForexPairDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/future/dtos/FutureDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/stock/dtos/StockDto.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/ExchangeServiceMock.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/ListingServiceMock.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/SecuritiesServiceMock.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/ExchangeObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/ForexPairObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/FutureObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/ListingObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/SecuritiesObjectMother.java
  stock-service/src/main/java/rs/banka4/stock_service/service/mock/generators/StockObjectMother.java
  stock-service/src/main/resources/db/migration/V2025.100.31.1743453733__change_inheritence_type_and_listings.sql
Labels: approved, size/XL, lgtm
