Repository RAF-SI-2024/Banka-4-Backend, pull requests merged in 2025-04, with the labels that each got.

#267 stock-service: add created_at column to orders
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/Order.java
  stock-service/src/main/resources/db/migration/V2025.204.01.1743505972__add_created_time_to_order.sql
Labels: size/S, approved, lgtm

#271 Completed whole Securities trading portal part from specification
  common/src/main/java/rs/banka4/rafeisen/common/test/BadUUIDGenerator.java
  stock-service/build.gradle.kts
  stock-service/src/main/java/rs/banka4/stock_service/StockServiceApplication.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/ListingController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/ListingApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/actuaries/db/MonetaryAmount.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/exchanges/db/Exchange.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/Listing.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/db/ListingDailyPriceInfo.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/ListingDetailsDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/ListingFilterDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/ListingInfoDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/OptionDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/PriceChangeDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/SecurityType.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/specific/ForexPairDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/specific/FutureDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/specific/StockDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/mapper/ListingDailyPriceInfoMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/mapper/ListingMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/specificaion/ListingSpecification.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/Option.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/Order.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/stock/db/Stock.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/BaseApiException.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/ListingNotFoundException.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/AssetRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/DailyListingsRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingDailyPriceInfoRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OptionsRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OrderRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/SecurityRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/ListingService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/OrderService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/ListingServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/OrderServiceImpl.java
  stock-service/src/main/resources/db/migration/V2025.204.01.1743519147__little_constraint_changes_and_add_used_to_orders.sql
  stock-service/src/test/java/rs/banka4/stock_service/integration/ListingTests.java
  stock-service/src/test/java/rs/banka4/stock_service/utils/AssetGenerator.java
  stock-service/src/test/java/rs/banka4/stock_service/utils/ExchangeGenerator.java
  stock-service/src/test/java/rs/banka4/stock_service/utils/ListingGenerator.java
  stock-service/src/test/resources/application.yml
  testlib/build.gradle.kts
  testlib/src/main/java/rs/banka4/testlib/integration/DbEnabledTest.java
  testlib/src/main/java/rs/banka4/testlib/integration/FlywayCleanerExtension.java
  testlib/src/main/java/rs/banka4/testlib/integration/IntegrationTest.java
  testlib/src/main/java/rs/banka4/testlib/integration/PSQLTestContainerConfig.java
Labels: approved, lgtm, size/XXL

#272 bugfix/add-premium-to-options
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/OptionDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/Option.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/ListingServiceImpl.java
  stock-service/src/main/resources/db/migration/V2025.204.03.1743704226__add_premium_to_options.sql
  stock-service/src/test/java/rs/banka4/stock_service/integration/ListingTests.java
  stock-service/src/test/java/rs/banka4/stock_service/utils/AssetGenerator.java
Labels: size/M, approved, lgtm

#270 user-service-fix: card search account number filter
  user-service/src/main/java/rs/banka4/user_service/repositories/CardRepository.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/CardServiceImpl.java
  user-service/src/test/java/rs/banka4/user_service/integration/SearchClientCardsTest.java
  user-service/src/test/java/rs/banka4/user_service/integration/generator/UserGenerator.java
  user-service/src/test/resources/testdata/SearchClientCardsTest_clientSearchCardsSuccessfully.json
Labels: approved, lgtm, size/L

#283 stock,user: enable 'test' profile in tests
  stock-service/src/test/resources/application.yml
  user-service/src/test/resources/application.yml
Labels: approved, size/XS, lgtm

#284 stock: enable permissive CORS in dev
  stock-service/src/main/java/rs/banka4/stock_service/security/PermissiveCorsConfig.java
  stock-service/src/main/java/rs/banka4/stock_service/security/SecurityConfig.java
Labels: size/M, approved, lgtm

#288 stock: add openapi config
  stock-service/src/main/java/rs/banka4/stock_service/StockServiceApplication.java
  stock-service/src/main/java/rs/banka4/stock_service/config/OpenAPIConfig.java
Labels: size/M, approved, lgtm

#285 Add new migration to drop of old data
  stock-service/src/main/java/rs/banka4/stock_service/runners/TestDataRunner.java
  stock-service/src/main/resources/db/migration/V2025.204.07.1743985700__drop_old_seeders.sql
Labels: size/M, approved, lgtm

#286 add id to listing info dto
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/dtos/ListingInfoDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/listing/mapper/ListingMapper.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/ListingTests.java
Labels: approved, size/XS, lgtm

#296 Fix/Added future and forex listings. Fixed retrofit problem
  stock-service/src/main/java/rs/banka4/stock_service/runners/TestDataRunner.java
Labels: size/S, approved, lgtm

#299 user/phone: fix phone number again
  user-service/src/main/java/rs/banka4/user_service/service/impl/ClientServiceImpl.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/EmployeeServiceImpl.java
Labels: size/S, approved, lgtm

#297 Feature/order creation
  stock-service/src/main/java/rs/banka4/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/OrderApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/db/Order.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/dtos/CreateOrderDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/dtos/CreateOrderPreviewDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/dtos/OrderDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/dtos/OrderPreviewDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/mapper/OrderMapper.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/AssetNotFound.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/ExchangeNotFound.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/RequiredPriceException.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ActuaryRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/ListingService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/OrderService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/ListingServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/OrderServiceImpl.java
  stock-service/src/test/java/rs/banka4/stock_service/generator/ActuaryObjectMother.java
  stock-service/src/test/java/rs/banka4/stock_service/generator/AssetObjectMother.java
  stock-service/src/test/java/rs/banka4/stock_service/generator/ExchangeObjectMother.java
  stock-service/src/test/java/rs/banka4/stock_service/generator/ListingObjectMother.java
  stock-service/src/test/java/rs/banka4/stock_service/generator/OrderObjectMother.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/order/OrderControllerTest.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/order/OrderServiceTest.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/order/TestDataFactory.java
  stock-service/src/test/java/rs/banka4/stock_service/unit/order/OrderServiceCreateOrderTests.java
Labels: approved, lgtm, size/XXL

#303 bugfix/add-active-to-options
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/Option.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OptionsRepository.java
  stock-service/src/main/resources/db/migration/V2025.204.11.1744404736__add_active_field_to_options.sql
Labels: approved, size/XS, lgtm

#304 Feature/add scheduled data updates for listings and options
  stock-service/src/main/java/rs/banka4/stock_service/domain/options/db/OptionsMaker.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/ExchangeAcronymNotFound.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ExchangeRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ForexRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OptionsRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/runners/TestDataRunner.java
  stock-service/src/main/java/rs/banka4/stock_service/utils/ListingsAndOptionsUpdatesScheduler.java
  stock-service/src/main/resources/application-dev.yml
  stock-service/src/main/resources/application.properties
Labels: approved, size/XL, lgtm

#292 Clean commit securities /me
  stock-service/build.gradle.kts
  stock-service/src/main/java/rs/banka4/stock_service/controller/SecuritiesController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/SecuritiesApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/responses/SecurityOwnershipResponse.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/responses/SecurityTypeDto.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/ListingRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OrderRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/SecuritiesService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/SecuritiesServiceImpl.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/SecuritiesControllerTest.java
  stock-service/src/test/java/rs/banka4/stock_service/unit/SecuritiesServiceImplTest.java
Labels: approved, size/XL, lgtm

#305 Feature/search orders
  stock-service/src/main/java/rs/banka4/stock_service/controller/OrderController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/OrderApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/dtos/OrderDto.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/OrderNotFound.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OrderRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/security/SecurityConfig.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/OrderService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/OrderServiceImpl.java
  stock-service/src/test/java/rs/banka4/stock_service/generator/OrderObjectMother.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/order/OrderServiceTest.java
  stock-service/src/test/java/rs/banka4/stock_service/integration/order/TestDataFactory.java
  stock-service/src/test/java/rs/banka4/stock_service/unit/order/OrderServiceSearchOrderTests.java
Labels: approved, lgtm, size/L

#308 Feature/order execution
  docker-compose.yml
  stock-service/src/main/java/rs/banka4/stock_service/config/AsyncConfig.java
  stock-service/src/main/java/rs/banka4/stock_service/config/RestTemplateConfig.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/SecuritiesController.java
  stock-service/src/main/java/rs/banka4/stock_service/controller/docs/SecuritiesApiDocumentation.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/orders/dtos/CreateFeeTransactionDto.java
  stock-service/src/main/java/rs/banka4/stock_service/domain/security/responses/SecurityOwnershipResponse.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/AlreadyUpdatedOrderStatus.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/InsufficientVolume.java
  stock-service/src/main/java/rs/banka4/stock_service/exceptions/InvalidOrderStatus.java
  stock-service/src/main/java/rs/banka4/stock_service/repositories/OrderRepository.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/OrderService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/abstraction/SecuritiesService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/OrderExecutionService.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/OrderServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/service/impl/SecuritiesServiceImpl.java
  stock-service/src/main/java/rs/banka4/stock_service/utils/ExecuteOrderScheduler.java
  stock-service/src/test/java/rs/banka4/stock_service/unit/SecuritiesServiceImplTest.java
  user-service/src/main/java/rs/banka4/user_service/config/WhiteListConfig.java
  user-service/src/main/java/rs/banka4/user_service/controller/TransactionController.java
  user-service/src/main/java/rs/banka4/user_service/controller/docs/TransactionApiDocumentation.java
  user-service/src/main/java/rs/banka4/user_service/domain/transaction/dtos/CreateFeeTransactionDto.java
  user-service/src/main/java/rs/banka4/user_service/service/abstraction/TransactionService.java
  user-service/src/main/java/rs/banka4/user_service/service/impl/TransactionServiceImpl.java
Labels: approved, lgtm, size/XXL

#309 ban junit 4
  buildSrc/src/main/kotlin/banka4.test-conventions.gradle.kts
  stock-service/src/test/java/rs/banka4/stock_service/integration/SecuritiesControllerTest.java
  stock-service/src/test/java/rs/banka4/stock_service/unit/order/OrderServiceSearchOrderTests.java
  testlib/build.gradle.kts
  user-service/src/test/java/rs/banka4/user_service/unit/authenticator/TotpServiceImplTest.java
Labels: approved, lgtm, size/L

#312 bank-service: add taxes entity and migration
  bank-service/src/main/java/rs/banka4/bank_service/domain/taxes/db/UserTaxDebts.java
  bank-service/src/main/resources/db/migration/V2025.204.15.1744749520__add_user_tax_debts_table.sql
Labels: size/M, approved, lgtm

#313 bank: remove over-verbose hibernate logs
  bank-service/src/test/resources/application.yml
Labels: approved, size/XS, lgtm

#314 Implement order approve and decline routes
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/OrderController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/OrderApiDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/exceptions/SettlementDatePassedException.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/OrderService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderServiceImpl.java
Labels: approved, lgtm, size/L

#315 Bank accounts endpoint
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/AccountController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/AccountApiDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/account/dtos/BankAccountDto.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/BankAccountService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/BankAccountServiceImpl.java
  bank-service/src/test/java/rs/banka4/bank_service/routes/AccountControllerTests.java
Labels: size/M, approved, lgtm

#316 Fix account number in orders
  bank-service/src/main/java/rs/banka4/bank_service/domain/orders/dtos/CreateOrderDto.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/transaction/dtos/CreateFeeTransactionDto.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderExecutionService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TransactionServiceImpl.java
  bank-service/src/test/java/rs/banka4/bank_service/generator/OrderObjectMother.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderControllerTest.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderServiceTest.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/TestDataFactory.java
Labels: size/M, approved, lgtm

#317 stock/order: add agent information in dto
  bank-service/src/main/java/rs/banka4/bank_service/domain/orders/dtos/OrderDto.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/orders/mapper/OrderMapper.java
  bank-service/src/test/java/rs/banka4/bank_service/generator/OrderObjectMother.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderControllerTest.java
Labels: size/S, approved, lgtm

#318 Endpoints for portfolio and profit
  bank-service/src/main/java/rs/banka4/bank_service/controller/SecuritiesController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/SecuritiesApiDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/security/responses/AssetTypeDto.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/security/responses/SecurityHoldingDto.java
  bank-service/src/main/java/rs/banka4/bank_service/repositories/AssetOwnershipRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/repositories/OrderRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/SecuritiesService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/SecuritiesServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/profit/ProfitCalculator.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/SecuritiesControllerTests.java
Labels: approved, lgtm, size/XXL

#321 Endpoint for current client taxes
  bank-service/src/main/java/rs/banka4/bank_service/controller/SecuritiesController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/SecuritiesApiDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/taxes/db/dto/UserTaxInfoDto.java
  bank-service/src/main/java/rs/banka4/bank_service/repositories/UserTaxDebtsRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/SecuritiesService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/SecuritiesServiceImpl.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/SecuritiesControllerTests.java
Labels: approved, lgtm, size/L

#320 add docs for accept route and options controller
  bank-service/src/main/java/rs/banka4/bank_service/controller/OptionsController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/OtcController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/OptionsApiDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/OtcApiDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/options/dtos/BuyOptionRequestDto.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/options/dtos/UseOptionRequest.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/OtcRequestService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OtcRequestServiceImp.java
  common/src/main/java/rs/banka4/rafeisen/common/exceptions/ErrorResponseHandler.java
Labels: approved, lgtm, size/L

#324 prow: only do CD on main
  .prow/build-images.yml
Labels: approved, size/XS, lgtm

#326 bank-service: make limit nullable in actuaries
  bank-service/src/main/java/rs/banka4/bank_service/domain/actuaries/db/ActuaryInfo.java
  bank-service/src/main/resources/db/migration/V2025.204.16.1744829000__make_limit_in_actuaries_nullable.sql
Labels: approved, size/XS, lgtm

#322 migrate to fifo calculation for unrealized profit
  bank-service/src/main/java/rs/banka4/bank_service/utils/profit/ProfitCalculator.java
Labels: size/M, approved, lgtm

#327 bank-service: bugfix: change get to post routes
  bank-service/src/main/java/rs/banka4/bank_service/controller/OptionsController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/OtcController.java
Labels: approved, size/XS, lgtm

#328 Endpoints and Schedulers for tax charge and calculations
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/TaxController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/TaxControllerDocumentation.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/taxes/db/dto/TaxableUserDto.java
  bank-service/src/main/java/rs/banka4/bank_service/repositories/UserTaxDebtsRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/TaxService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/SecuritiesServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TaxServiceImp.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/tax/TaxCalculationUtill.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/SecuritiesControllerTests.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/TaxTests.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/generator/UserTaxGenerator.java
Labels: approved, lgtm, size/XXL

#329 Refactor tax profit
  bank-service/src/main/java/rs/banka4/bank_service/repositories/UserTaxDebtsRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/ProfitCalculationService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/TaxCalculationService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/ProfitCalculationServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/SecuritiesServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TaxCalculationServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TaxServiceImp.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/SecuritiesControllerTests.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/generator/PortfolioGenerator.java
Labels: approved, size/XL, lgtm

#330 Feature/add tax to db
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/ProfitCalculationService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/TaxService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderExecutionService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/ProfitCalculationServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/SecuritiesServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TaxServiceImp.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/SecuritiesControllerTests.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/TaxTests.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/generator/PortfolioGenerator.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/profit/ProfitCalculatorTest.java
Labels: approved, size/XL, lgtm

#325 Fix/ Readme PSQL command was outdated
  README.md
Labels: bug, approved, size/XS, lgtm

#333 Bugfix/missing path variable accept otc req
  bank-service/src/main/java/rs/banka4/bank_service/controller/OtcController.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/docs/OtcApiDocumentation.java
Labels: size/S, approved, lgtm

#332 bank: add a route that resets all data
  bank-service/src/main/java/rs/banka4/bank_service/config/WhiteListConfig.java
  bank-service/src/main/java/rs/banka4/bank_service/config/filters/InvalidRouteFilter.java
  bank-service/src/main/java/rs/banka4/bank_service/controller/E2ETestController.java
  bank-service/src/main/java/rs/banka4/bank_service/runners/TestDataRunner.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TaxServiceImp.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/DataSourceService.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/TaxTests.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/seeder/TestDataSeeder.java
  common/src/main/java/rs/banka4/rafeisen/common/exceptions/RouteNotFound.java
Labels: approved, lgtm, size/XXL

#334 Fix client trading issue
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderServiceImpl.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderControllerTest.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/order/OrderServiceCreateOrderTests.java
Labels: size/M, approved, lgtm

#331 Fix/ unmapped property createdAt in ExchangeDto
  bank-service/src/main/java/rs/banka4/bank_service/domain/exchanges/dtos/ExchangeDto.java
Labels: approved, size/XS, lgtm

#335 stock-service: add latestStockPrice to OtcRequestDto
  bank-service/src/main/java/rs/banka4/bank_service/controller/OtcController.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/trading/db/OtcMapper.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/trading/db/dtos/OtcRequestDto.java
  bank-service/src/test/java/rs/banka4/bank_service/generator/OtcRequestGen.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/OtcTests.java
Labels: approved, lgtm, size/L

#338 Fix amount not mapped properly
  bank-service/src/main/java/rs/banka4/bank_service/domain/trading/db/dtos/OtcRequestUpdateDto.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/OtcTests.java
Labels: approved, size/XS, lgtm

#339 bank-service/requests: add order by last modified
  bank-service/src/main/java/rs/banka4/bank_service/repositories/OtcRequestRepository.java
Labels: approved, size/XS, lgtm

#337 security: allow patch requests
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
Labels: approved, size/XS, lgtm

#336 Bugfix/order creation
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
  bank-service/src/main/java/rs/banka4/bank_service/domain/orders/dtos/CreateOrderPreviewDto.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/DataSourceService.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderControllerTest.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderServiceTest.java
Labels: approved, lgtm, size/L

#342 Fix actuary search not working
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/EmployeeServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/DataSourceService.java
Labels: size/S, approved, lgtm

#323 Feature/ Add daily listing price history scheduler
  bank-service/src/main/java/rs/banka4/bank_service/repositories/ListingDailyPriceInfoRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/repositories/ListingRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/ListingInfoScheduler.java
Labels: approved, lgtm, size/L

#343 Fix/ change ldpi last price calculation
  bank-service/src/main/java/rs/banka4/bank_service/utils/ListingInfoScheduler.java
Labels: approved, size/XS, lgtm

#344 cd: automatically push front to prod every time
  .prow/build-images.yml
Labels: size/S, approved, lgtm

#345 cd: obscure HARBOR_PASSWORD from stdout
  .prow/build-images.yml
Labels: approved, size/XS

#346 updated account number range
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/AccountServiceImpl.java
Labels: approved, size/XS, lgtm

#347 cd: add verbose logging to CD job
  .prow/build-images.yml
Labels: approved, size/XS, lgtm

#350 hack out orders or something idk
  bank-service/src/main/java/rs/banka4/bank_service/domain/actuaries/db/MonetaryAmount.java
  bank-service/src/main/java/rs/banka4/bank_service/repositories/AssetOwnershipRepository.java
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/AssetOwnershipService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/AssetOwnershipServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/tx/executor/InterbankTxExecutor.java
  bank-service/src/main/java/rs/banka4/bank_service/tx/otc/config/InterbankService.java
  bank-service/src/main/java/rs/banka4/bank_service/tx/otc/mapper/InterbankOtcMapper.java
  bank-service/src/main/java/rs/banka4/bank_service/tx/otc/service/impl/InterbankOtcServiceImpl.java
Labels: approved, lgtm, size/L

#351 fix cors config being too lax
  bank-service/src/main/java/rs/banka4/bank_service/config/SecurityConfig.java
Labels: approved, size/XS, lgtm

#352 Fix/special tx
  bank-service/src/main/java/rs/banka4/bank_service/service/abstraction/TransactionService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/LoanServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderExecutionService.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/banka4/bank_service/tx/executor/InterbankTxExecutor.java
  bank-service/src/main/java/rs/banka4/bank_service/utils/loans/LoanInstallmentScheduler.java
  bank-service/src/test/java/rs/banka4/bank_service/integration/order/OrderServiceTest.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/loan/LoanInstallmentSchedulerTest.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/loan/ManageLoansTests.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/order/OrderServiceCreateOrderTests.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/transaction/TransactionServiceCreateTests.java
  bank-service/src/test/java/rs/banka4/bank_service/unit/transaction/TransactionServiceProcessingTests.java
Labels: approved, size/XL, lgtm
